services: 
  user-service1: 
      image: andreashp60/auktionshus:user-service
      ports:  
      - "8080:80" 
      environment: 
      - MongoDBConct=mongodb+srv://auktionshus:jamesbond@auktionshus.aeg6tzo.mongodb.net/test
