services:    
  rabbitmq-dev: 
     image: rabbitmq:management 
     ports: 
     - "15672:15672" 
     - "5672:5672"
     environment: 
      - MongoDBConct=mongodb+srv://auktionshus:jamesbond@auktionshus.aeg6tzo.mongodb.net/test
  worker:
      image: marththecreater/auktionshuset:worker
      ports:
      - "8081:80"
      depends_on:
      - rabbitmq-dev
  auktionsapi:
      image: marththecreater/auktionshuset:auktionapi
      ports:
      - "8082:80"
      depends_on:
      - rabbitmq-dev
