services: 
  user-service: 
      image: andreashp60/auktionshus:user-service
      ports:  
      - "8080:80" 
      environment: 
      - MongoDBConct=mongodb+srv://auktionshus:jamesbond@auktionshus.aeg6tzo.mongodb.net/test
      - DatabaseName=Auktionshus
      - Collection=User
  product-service: 
      image: andreashp60/auktionshus:product
      ports:  
      - "8083:80" 
      environment: 
      - MongoDBConct=mongodb+srv://auktionshus:jamesbond@auktionshus.aeg6tzo.mongodb.net/test
  nginx: 
     image: loadbalancer:latest 
     volumes: 
     - ./nginx.conf:/etc/nginx/nginx.conf:ro 
     depends_on: 
     - user-service
     ports: 
     - "4000:4000"     
  rabbitmq-dev: 
     image: rabbitmq:management 
     ports: 
     - "15672:15672" 
     - "5672:5672"
  sender:
      image: andreashp60/auktionshus:send
      ports:
      - "8081:80"
  receive:
      image: andreashp60/auktionshus:receive
      ports:
      - "8082:80"