services:    
  rabbitmq-dev: 
     image: rabbitmq:management 
     ports: 
     - "15672:15672" 
     - "5672:5672"
     environment: 
      - MongoDBConct=mongodb+srv://auktionshus:jamesbond@auktionshus.aeg6tzo.mongodb.net/test
      - DatabaseName=Auktionshus
      - Collection=User
  worker:
      image: marththecreater/auktionshuset:worker
      ports:
      - "8081:80"
      depends_on:
      - rabbitmq-dev
  auktionsapi:
      image: marththecreater/auktionshuset:auktionsapi
      ports:
      - "8082:80"
      depends_on:
      - rabbitmq-dev
  kundeAPI:
      image: marththecreater/auktionshuset:customer
      ports:
      - "8083:80"
  vareAPI:
      image: marththecreater/auktionshuset:product
      ports:
      - "8084:80"
  nginx: 
     image: nginx:latest 
     volumes: 
     - ./nginx.conf:/etc/nginx/nginx.conf:ro 
     depends_on: 
     - auktionsapi
     - kundeAPI
     - vareAPI
     ports: 
     - "4000:4000"  
